management_jobs/customer/urls.py
from django.urls import path, re_path
from customer import views

app_name = 'customer'

urlpatterns = [
    re_path('customer/edit-job/(?P<slug>[\w_-]+)/?$', views.edit_job, name='edit_job'),
    path('customer/add-job', views.add_job, name='add_job'),
    path('customer/add-customer', views.add_customer, name='add_customer'),
    re_path('customer/edit-customer/(?P<slug>[\w_-]+)/?$', views.edit_customer, name='edit_customer'),
    re_path('^customer/(?P<slug>[\w_-]+)/?$', views.customer_job, name='customer'),  # essa é pra listar os dados sem editar
    path('job', views.job_list, name='job'),
    path('customer-list', views.customer_list, name='customer_list'),
    path('', views.index, name='index')
]

management_jobs/management_jobs/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('customer.urls', namespace='customer')),
]

management_jobs/customer/models.py
from django.db import models
from django.db.models import signals
from django.urls import reverse


class Customer(models.Model):
    name = models.CharField("Cliente", max_length=200)
    dtt_record = models.DateTimeField("Data de Inserção", auto_now_add=True, blank=True)
    email = models.EmailField("E-mail", max_length=50)
    phone = models.CharField("Telefone", max_length=15)
    slug = models.SlugField('Slug', max_length=200, unique=True, blank=True,
                            help_text='Adicione uma slug com palavras separadas por hifens para ou deixe em branco para preenchimento automático.')
    active = models.BooleanField("Ativo", default=True)

    objects = models.Manager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('customer:customer', args=[self.slug])


class Job(models.Model):
    name = models.CharField("Serviço", max_length=200)
    price = models.DecimalField("Valor Cobrado", max_digits=10, decimal_places=2)
    slug = models.SlugField('Slug', max_length=200, unique=True, blank=True,
                            help_text='Adicione uma slug com palavras separadas por hifens para ou deixe em branco para preenchimento automático.')
    dtt_record = models.DateTimeField("Data de Inserção", auto_now_add=True, blank=True)

    objects = models.Manager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('customer:job', args=[self.slug])


class CustomerJob(models.Model):
    customer = models.ForeignKey(Customer, related_name="customer_job", on_delete=models.CASCADE)
    job = models.ForeignKey(Job, related_name='job_type', on_delete=models.PROTECT)
    recurrent = models.BooleanField("Recorrente")
    dtt_start = models.DateField("Data de Inicio")
    dtt_end = models.DateField("Data de Termino")
    dtt_record = models.DateTimeField("Data de Inserção", auto_now_add=True, blank=True)

    objects = models.Manager()


from libs.signals import slug_pre_save

signals.pre_save.connect(slug_pre_save, sender=Customer)
signals.pre_save.connect(slug_pre_save, sender=Job)

management_jobs/customer/forms.py
from django import forms

from .models import Customer, Job


class FormCustomer(forms.ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'

management_jobs/customer/views.py
from django.db.models import Count
from django.shortcuts import render, get_object_or_404

from .models import Customer, Job
from .forms import FormCustomer


def index(request):
    context = {}
    template_name = 'customer/index.html'
    return render(request, template_name, context)


def customer_list(request):
    context = {}
    template_name = 'customer/customer_list.html'
    context['customer_list'] = Customer.objects.annotate(qt_customer=Count('customer_job')).filter(qt_customer__gt=0)
    return render(request, template_name, context)


def customer_job(request, slug):
    context = {}
    customer = get_object_or_404(Customer, slug=slug)

    # Função filter, filtra os elementos de acordo com o campo que eu informar
    # joblist = customer.customer_job.filter(active=True).order_by('dtt_record', 'customer')
    joblist = customer.customer_job.order_by('dtt_record', 'customer')

    context['customer_jobs'] = joblist
    context['customer'] = customer
    template_name = 'customer/customer_job.html'

    return render(request, template_name, context)


def edit_customer(request, slug):
    context = {}
    customer = get_object_or_404(Customer, slug=slug)
    template_name = 'customer/edit_customer.html'

    if request.method == 'POST':
        form = FormCustomer(request.POST, instance=customer)
        if form.is_valid():
            form.save()
            form = FormCustomer(instance=customer)
            context['slug'] = customer.slug
            context['success'] = True
    else:
        form = FormCustomer(instance=customer)

    context['form'] = form

    return render(request, template_name, context)


def add_customer(request):
    context = {}
    template_name = 'customer/add_customer.html'

    if request.method == 'POST':
        form = FormCustomer(request.POST)
        if form.is_valid():
            form.save()
            context['success'] = True
            form = FormCustomer()
    else:
        form = FormCustomer()

    context['form'] = form

    return render(request, template_name, context)


def job_list(request):
    context = {}
    jobs = Job.objects.order_by('dtt_record')

    context['jobs'] = jobs
    template_name = 'customer/job.html'

    return render(request, template_name, context)


def edit_job(request, slug):
    context = {}
    job = get_object_or_404(Job, slug=slug)

    context['job'] = job

    template_name = 'customer/edit_job.html'

    return render(request, template_name, context)


def add_job(request):
    context = {}
    template_name = 'customer/add_job.html'
    return render(request, template_name, context)

management_jobs/customer/templates/customer/add_customer.html
{% extends 'customer/base.html' %}

{% block content %}

<div class="container pt-3">
    <div class="row justify-content-center">
        <div class="col-6">
            <div class="display-6" style="text-align: center;">Adicionar Cliente</div>
            <form name="new-customer" id="new-customer" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="text-danger">{{ form.non_fields_errors }}</div>

                <!-- Name input -->
                <div class="form-outline mb-4">
                    <input type="text" name="name" id="name" class="form-control" value="{{ form.name.value|default_if_none:'' }}"/>
                    <label class="form-label" for="name">Nome</label>
                </div>

                <!-- Email input -->
                <div class="form-outline mb-4">
                    <input type="email" name="email" id="email" class="form-control" value="{{ form.email.value|default_if_none:'' }}"/>
                    <label class="form-label" for="email">E-mail</label>
                </div>

                <div class="form-outline mb-4">
                    <input type="text" name="phone" id="phone" class="form-control" value="{{ form.phone.value|default_if_none:'' }}"/>
                    <label class="form-label" for="phone">Telefone</label>
                </div>

                <!-- Checkbox -->
                <div class="form-check d-flex justify-content-start mb-4">
                    <input class="form-check-input me-2" type="checkbox" value="{{ form.active.value|default_if_none:True }}" name="active" id="active" checked/>
                    <label class="form-check-label" for="active">
                        Ativo
                    </label>
                </div>

                <!-- Submit button -->
                <button type="submit" class="btn btn-primary btn-block mb-4">Adicionar</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

management_jobs/customer/templates/customer/add_job.html
{% extends 'customer/base.html' %}

{% block content %}

<div class="container pt-3">
    <div class="row justify-content-center">
        <div class="col-6">
            <div class="display-6" style="text-align: center;">Adicionar Job</div>
            <form>
                <!-- Name input -->
                <div class="form-outline mb-4">
                    <input type="text" id="form4Example1" class="form-control" value=""/>
                    <label class="form-label" for="form4Example1">Job</label>
                </div>

                <!-- Email input -->
                <div class="form-outline mb-4">
                    <input type="text" id="form4Example2" class="form-control" value=""/>
                    <label class="form-label" for="form4Example2">Valor cobrado</label>
                </div>

                <div class="form-outline mb-4">
                    <input type="text" id="form4Example1" class="form-control" value=""/>
                    <label class="form-label" for="form4Example1">slug</label>
                </div>


                <!-- Submit button -->
                <button type="submit" class="btn btn-primary btn-block mb-4">Adicionar</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

management_jobs/customer/templates/customer/customer_job.html
{% extends 'customer/base.html' %}
{#{% load humanize %}#}


{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="display-6">{{ customer.name }}</div>
        <div class="small"><i class="fa-solid fa-envelope"></i> {{ customer.email }}</div>
        <div class="small">
            <a href="https://api.whatsapp.com/send?phone=+55{{ customer.phone }}&text=Ola." class="link-success">
                <i class="fa-brands fa-whatsapp"></i> {{ customer.phone }}</a>
        </div>
    </div>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Serviço</th>
            <th scope="col">Recorrente</th>
            <th scope="col">Data Inicio</th>
            <th scope="col">Data Fim</th>
            <th scope="col">Valor R$</th>
        </tr>
        </thead>
        <tbody>
        {% for customer_job in customer_jobs %}

            <tr>
                <th scope="row">{{ customer_job.id }}</th>
                <td>{{ customer_job.job }}</td>
                <td>
                    {% if customer_job.recurrent %}
                        <i class="fa fa-check-circle text-success"></i>
                    {% else %}
                        <i class="fa fa-minus text-muted"></i>
                    {% endif %}
                </td>
                <td>{{ customer_job.dtt_start|date:'d/m/Y' }}</td>
                <td>{{ customer_job.dtt_end|date:'d/m/Y' }}</td>
                <td>R$ {{ customer_job.job.price|floatformat:"2" }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content %}

management_jobs/customer/templates/customer/customer_list.html
{% extends 'customer/base.html' %}

{% block content %}

    <div class="display-6 my-5">
        Clientes Ativos
    </div>

    <div class="alert bg-light">
        <a class="btn btn-info" href="{% url 'customer:add_customer' %}">Novo Cliente</a>
        {# outros botões de utilidade vão aqui ou uma busca por cliente, etc. entdenda como uma barra da área de listagem de clientes. #}
    </div>

    {% if customer_list %}

        {# tabela de listagem de cliente #}
        <table class="table table-hover table-responsive table-striped mx-auto">
            {#  ajuste de classes aqui, incluindo o responsive, stripped e margem automatica #}
            <thead>
            <tr class="text-start">
                <th scope="col" class="w-5 text-center"><i class="fa fa-pencil text-muted"></i></th>
                <th scope="col" class="w-5">ID</th>
                <th scope="col" class="w-auto">Cliente</th>
                <th scope="col" class="w-25">Preço</th>
                <th scope="col" class="w-25">Cliente Ativo</th>
                <th scope="col" class="w-25">Data de Inserção</th>
            </tr>
            </thead>
            <tbody class="text-start">
            {% for customer in customer_list %}
                <tr class="table-row">
                    <td class="text-center">
                        <a href="{% url 'customer:edit_customer' customer.slug %}"
                           class="openPopup text-center btn btn-sm btn-info">
                            Editar
                        </a>
                    </td>
                    <td scope="row" class="text-end me-2">
                        <a class="customer-job-link"
                           href="{{ customer.get_absolute_url }}">{{ customer.id }}</a></td>
                    <td><a class="customer-job-link"
                           href="{{ customer.get_absolute_url }}">{{ customer.name }}</a></td>
                    <td><a class="customer-job-link"
                           href="{{ customer.get_absolute_url }}">[00.00]</a></td>
                    <td><a class="customer-job-link"
                           href="{{ customer.get_absolute_url }}">{{ customer.active }}</a></td>
                    <td><a class="customer-job-link"
                           href="{{ customer.get_absolute_url }}">{{ customer.dtt_record|date:'d/m/Y H:i:s' }}</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}

{% endblock content %}

management_jobs/customer/templates/customer/edit_customer.html
{% extends 'customer/base.html' %}

{% block content %}

<div class="container pt-3">
    <div class="row justify-content-center">
        <div class="col-6">
            <div class="display-6" style="text-align: center;">Alterar Cliente</div>
            <form name="new-customer" id="new-customer" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="text-danger">{{ form.non_fields_errors }}</div>

                <!-- Name input -->
                <div class="form-outline mb-4">
                    <input type="text" name="name" id="name" class="form-control" value="{{ form.name.value|default_if_none:'' }}"/>
                    <label class="form-label" for="name">Nome</label>
                </div>

                <!-- Email input -->
                <div class="form-outline mb-4">
                    <input type="email" name="email" id="email" class="form-control" value="{{ form.email.value|default_if_none:'' }}"/>
                    <label class="form-label" for="email">E-mail</label>
                </div>

                <div class="form-outline mb-4">
                    <input type="text" name="phone" id="phone" class="form-control" value="{{ form.phone.value|default_if_none:'' }}"/>
                    <label class="form-label" for="phone">Telefone</label>
                </div>

                <!-- Checkbox -->
                <div class="form-check d-flex justify-content-start mb-4">
                    <input class="form-check-input me-2" type="checkbox" value="{{ form.active.value|default_if_none:True }}" name="active" id="active" checked/>
                    <label class="form-check-label" for="active">
                        Ativo
                    </label>
                </div>

                <!-- Submit button -->
                <button type="submit" class="btn btn-primary btn-block mb-4">Alterar</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

management_jobs/customer/templates/customer/edit_job.html
{% extends 'customer/base.html' %}

{% block content %}

<div class="container pt-3">
    <div class="row justify-content-center">
        <div class="col-6">
            <div class="display-6" style="text-align: center;">Alterar Job</div>
            <form>
                <!-- Name input -->
                <div class="form-outline mb-4">
                    <input type="text" id="form4Example1" class="form-control" value="{{ job.name }}"/>
                    <label class="form-label" for="form4Example1">Job</label>
                </div>

                <!-- Email input -->
                <div class="form-outline mb-4">
                    <input type="text" id="form4Example2" class="form-control" value="{{ job.price }}"/>
                    <label class="form-label" for="form4Example2">Valor cobrado</label>
                </div>

                <div class="form-outline mb-4">
                    <input type="text" id="form4Example1" class="form-control" value="{{ job.slug }}"/>
                    <label class="form-label" for="form4Example1">slug</label>
                </div>


                <!-- Submit button -->
                <button type="submit" class="btn btn-primary btn-block mb-4">Alterar</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

management_jobs/customer/templates/customer/index.html
{% extends 'customer/base.html' %}


{% block content %}

    <div class="alert alert-success">Você acessou a área com sucesso. Aqui será exibido informações iniciais e a partir do menu, você vai selecionar a área que deseja acessar.</div>

{% endblock content %}

management_jobs/customer/templates/customer/job.html
{% extends 'customer/base.html' %}

{% block content %}
    <div class="alert bg-light">
        <a class="btn btn-info" href="{% url 'customer:add_job' %}">Novo Job</a>
        {# outros botões de utilidade vão aqui ou uma busca por cliente, etc. entdenda como uma barra da área de listagem de clientes. #}
    </div>

    {% if jobs %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col" class="w-5 text-center"><i class="fa fa-pencil text-muted"></i></th>
                    <th scope="col">Serviço</th>
                    <th scope="col">Preço</th>
                    <th scope="col">Data de Inserção</th>
                </tr>
            </thead>
            <tbody>
            {% for job in jobs %}
                <tr class="">
                    <td class="text-center">
                        <a href="{% url 'customer:edit_job' job.slug %}"
                           class="openPopup text-center btn btn-sm btn-info">
                            Editar
                        </a>
                    </td>
                    <td>{{ job.name }}</td>
                    <td>R$ {{ job.price }}</td>
                    <td>{{ job.dtt_record|date:'d/m/Y H:i:s' }}</td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}

{% endblock content %}

management_jobs/management_jobs/templates/customer/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> {# esse comando ajusta a tela para zoom = 100% no responsivo/mobile. Faça o teste sem ele pra entender #}
    <link href="{{ STATIC_URL }}customer/plugins/mdb/css/mdb.min.css" rel="stylesheet"/>
    <link href="{{ STATIC_URL }}customer/css/style.css" />

    <title>Management Jobs</title>
</head>
<body>
    {% block navbar %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <botton class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#myNavButtons" aria-controls="myNavButtons" aria-expanded="false" aria-label="Toggle navigation" ><i class="fas fa-bars"></i></botton>
                <div class="collapse navbar-collapse" id="myNavButtons">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'customer:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'customer:customer_list' %}">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'customer:job' %}">Jobs</a>
                        </li>

                    </ul>

                </div>
            </div>
        </nav>
    {% endblock navbar %}


    <section id="container" class="container-fluid">
        {% block content %}
        {% endblock content %}
    </section>

    <script type="text/javascript" src="{{ STATIC_URL }}customer/plugins/mdb/js/mdb.min.js"></script>
    {% if success %}
        <scrip>
            alert('Agora foi');
        </scrip>
    {% endif %}
</body>
</html>